# Generated by Django 3.2.22 on 2023-11-06 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(upload_to='category/')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('towndelivery', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10)),
                ('phone', models.CharField(default='', max_length=15)),
                ('fname', models.CharField(default='', max_length=100)),
                ('lname', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price2', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('trending', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5, null=True)),
                ('available', models.IntegerField()),
                ('offer', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5)),
                ('outofstalk', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5)),
                ('category', models.ManyToManyField(to='administrator.Category')),
                ('description', models.ManyToManyField(to='administrator.Description')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='uploads/prouct')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='uploads/prouct')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='uploads/prouct')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='uploads/prouct')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sites_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=256)),
                ('linkedin', models.CharField(max_length=256)),
                ('shopify', models.CharField(max_length=256)),
                ('facebook', models.CharField(max_length=256)),
                ('instagram', models.CharField(max_length=256)),
                ('twitter', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=20)),
                ('map', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=1, max_digits=5)),
                ('height', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(default='profile.svg', upload_to='')),
                ('phone', models.CharField(default='', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prce', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.city')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=100)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10)),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.carttoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_complete', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10)),
                ('order_status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10)),
                ('payment_status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10)),
                ('pickup_status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.item')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.deliverylocations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.itemimg'),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(blank=True, to='administrator.Sizes'),
        ),
        migrations.AddField(
            model_name='deliverylocations',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.station'),
        ),
        migrations.AddField(
            model_name='deliverylocations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.country'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('price', models.IntegerField(null=True)),
                ('checked', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.item')),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.carttoken')),
            ],
        ),
    ]
