# Generated by Django 3.2.22 on 2023-11-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(blank=True, to='administrator.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.ManyToManyField(blank=True, to='administrator.Description'),
        ),
    ]
